language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew test
  - sonar-scanner
addons:
  sonarqube:
    organization: igorperikov-github
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $SONAR_BOT_TOKEN